{% set version = "1.11" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-markdown
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/markdown_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/markdown/markdown_{{ version }}.tar.gz
  sha256: 47fc61755a952ce9716c12de2daf7940fcf306747bd47ad31dd364bbccca5f14

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ posix }}zip             # [win]
  host:
    - r-base
    - r-commonmark
    - r-mime >=0.3
    - r-xfun
  run:
    - r-base
    - r-commonmark
    - r-mime >=0.3
    - r-xfun

test:
  commands:
    - $R -e "library('markdown')"           # [not win]
    - "\"%R%\" -e \"library('markdown')\""  # [win]

about:
  home: https://github.com/rstudio/markdown
  license: GPL-2.0-only
  summary: Provides R bindings to the 'Sundown' Markdown rendering library (<https://github.com/vmg/sundown>). Markdown is a plain-text formatting syntax that can be converted to 'XHTML' or other formats. See <http://en.wikipedia.org/wiki/Markdown> for more information about Markdown.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
