{% set version = '0.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-markdown
  version: {{ version|replace("-", "_") }}

source:
  fn: markdown_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/markdown_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/markdown/markdown_{{ version }}.tar.gz
  sha256: 538fd912b2220f2df344c6cca58304ce11e0960de7bd7bd573b3385105d48fed

build:
  merge_build_host: True  # [win]
  number: 2
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-mime >=0.3

  run:
    - r-base
    - r-mime >=0.3
    - xorg-libxrender 0.9.10

test:
  commands:
    - $R -e "library('markdown')"  # [not win]
    - "\"%R%\" -e \"library('markdown')\""  # [win]

about:
  home: https://github.com/rstudio/markdown
  license: GPL-2
  summary: Provides R bindings to the 'Sundown' 'Markdown' rendering library (https://github.com/vmg/sundown).
    'Markdown' is a plain-text formatting syntax that can be converted to 'XHTML' or
    other formats. See http://en.wikipedia.org/wiki/Markdown for more information about
    'Markdown'.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
