# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangtarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_ctarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "hDmOMpPzUDKSgpKo13xVqkAK5tSJ9/IzAPgso1t5bK7ifxS8g5XOrmz3FtYCEv1BCcjH21x2bzJrHygoNbHGXwmfa1n+9b3jTAm0Huqh2t5RmH+etZ/huvi+oTRa3breDRnN6vS8bq2bUqV6tRlL3xUW9xtV8tIJXO6hzoLLpBM/uZRc3UgC8LQjYdvJyHIdtb8Jq/v0c0nyn35FMZHQkFOI3Y5DlLdLbXgUR+kh0V/wp3QUp4TDnHPx6ZsdMAdN/X7moKZsRfIo39PUZ9MDAwixb2zJkER27J0nEvGF07Kc0eAyhQO0LsAkcY6ZtKHjnfu5/9iZeK878DWViDhXFOY488NZ98wLDvpjIl7Ru/LpiRVD+kjLT6wV3hnFdHC5IhzPWyZcffiW/hCAHwSTJOGRcf6XMTPsZeaAdG0gVv4gUUozp+bnkg1nyIPiW9BKnK0yPgQoZYGPhK+tMIDo6J2CtMyDh15z33gPAm/wneXdA1AZvm9eCyDZ7AJfviBDvnT0xnBfqp5dtGGXIdN61tBJ1pDPTyaHgLoTHsgepFOLOfPV1g0sESUExtspqfKFx4iEFRZwYbvX6f+YaVrYL/GYKPTZe6CIArIBQenn5K+hcYghx9N644rAR31gjv6D72tFky7fg6Svoi7QcHAUtuDF2fMvOR3X5oSuUVBLkaE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml