appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default, win: azure}
travis:
  secure: {BINSTAR_TOKEN: hDmOMpPzUDKSgpKo13xVqkAK5tSJ9/IzAPgso1t5bK7ifxS8g5XOrmz3FtYCEv1BCcjH21x2bzJrHygoNbHGXwmfa1n+9b3jTAm0Huqh2t5RmH+etZ/huvi+oTRa3breDRnN6vS8bq2bUqV6tRlL3xUW9xtV8tIJXO6hzoLLpBM/uZRc3UgC8LQjYdvJyHIdtb8Jq/v0c0nyn35FMZHQkFOI3Y5DlLdLbXgUR+kh0V/wp3QUp4TDnHPx6ZsdMAdN/X7moKZsRfIo39PUZ9MDAwixb2zJkER27J0nEvGF07Kc0eAyhQO0LsAkcY6ZtKHjnfu5/9iZeK878DWViDhXFOY488NZ98wLDvpjIl7Ru/LpiRVD+kjLT6wV3hnFdHC5IhzPWyZcffiW/hCAHwSTJOGRcf6XMTPsZeaAdG0gVv4gUUozp+bnkg1nyIPiW9BKnK0yPgQoZYGPhK+tMIDo6J2CtMyDh15z33gPAm/wneXdA1AZvm9eCyDZ7AJfviBDvnT0xnBfqp5dtGGXIdN61tBJ1pDPTyaHgLoTHsgepFOLOfPV1g0sESUExtspqfKFx4iEFRZwYbvX6f+YaVrYL/GYKPTZe6CIArIBQenn5K+hcYghx9N644rAR31gjv6D72tFky7fg6Svoi7QcHAUtuDF2fMvOR3X5oSuUVBLkaE=}
bot:
  automerge: true
